### ISSUE TITLE
Rotating camera moving to point 0 (ceiling)?

### ISSUE THREAD

**Issue by WebWire-NL** [guino/LSCOutdoor1080P#21]
I have a rotating camera and made the hack by replacing the binaries to the old version, it works well on the outdoor camera's but the indoor camera keeps pointing to the ceiling. I have motion tracking on and i use the Smart Life app on Android, anyone experiencing the same issue?

**Comment by guino** [comment]
https://github.com/guino/Merkury1080P/issues/59#issuecomment-2305487820
