### ISSUE TITLE
Rotatable Camera (Dual Band version) also works  

### ISSUE THREAD

**Issue by FlexxFR** [guino/LSCOutdoor1080P#22]
Very similar, same steps also works for the (newer?) dual-band version.
![image](https://github.com/user-attachments/assets/5de65721-f27d-41cd-854f-2e917e92373f)

It shipped with 3.10.83 by default and there was an update available.
After the hack it runs on the patched 2.10.36.
RTSP works, PTZ controls also work.

NMAP scan shows now 2 telnet sessions are available:
port 23, busybox telnet
port 24 the anonymous telnet.

--> As the 2nd telnet has to be anoymous to save SD write actions (as explained somewhere), why is this not applicable for the busybox telnet?

There is also something running on port 8090. But not mentioned in this write-up. What is this?

Is it also possible to get the "sub"stream, (low res) as rstp?

**Comment by FlexxFR** [comment]
Maybe I was to optimistic.
It works, but the config is not very stable. When the RTSP stream is accessed the cam crashed after a few minutes. I tried to connect it to frigate, it works, but after few minutes the feed crashed and the device is offline. A reboot works, but again only for a few minutes.

Is this a known issue? Is there anything to troubleshoot?

**Comment by guino** [comment]
I think I have seen some people running 3.10.68 working without issues, but there are reports of instability on versions 3.10.78 and higher. We probably need to inspect the new application version and see if we can enable RTSP on it directly (without downgrading to 2.10.36), but if there's no RTSP code in it, there's not much that can be done. 

You should telnet in and check resources like memory usage, to make sure it it's not running out -- also, if you DONT connect to RTSP: does it continue to work normally (without crashing)?

**Comment by FlexxFR** [comment]
Let's see. I disabled frigate, so RTSP is available (and working) but not used continuously. 
It still running the patched 2.10.36 firmware. App is working, normal HA plug-in is working. Let see, how stable this is.

This weekend I can re-enable RTSP and login with telnet and check resources and logs (if I can manage ;)). 

Would it be possible to get the low quality stream via RTSP (so it would use less resources?)

**Comment by ricardowpv** [comment]
Yesterday I bought a new outdoor variant of this camera. This one is also dual band and shipped with 3.10.73. I used method 3 and had the same problems; it crashed after a few minutes with Frigate using the RTSP stream. 

I took the SD-card out and updated it to 3.202.8. After the update I put it back in and RTSP was still working. Its working for over 2 hours now while Frigate is running without crashing.

The update:
![IMG_20240907_123638](https://github.com/user-attachments/assets/1276599e-d62f-448f-b058-56dc4c6e6017)

After update:
![IMG_20240907_123812](https://github.com/user-attachments/assets/fbf5fa6f-ea97-4106-be5c-bd5b37c1cc55)

After putting SD-card back in:
![IMG_20240907_123824](https://github.com/user-attachments/assets/f4255361-78f4-4f32-a023-3a05b80b6119)

**Comment by FlexxFR** [comment]
Interesting, but I don't understand it???
How could a firmware update, that you do not use when booting from ssd (because then still the older 2.10.36 patched version is used, have any effect?

At least, without RTSP used, the 2.10.36 firmware is stable and camera is still working via the app.

**Comment by guino** [comment]
@ricardowpv Thank you for the information -- that's great to know, thank you for the feedback!

@FlexxFR I know this may be confusing but when we're doing option 3 we're not really using '2.10.36' entirely -- we're only using the 'main application' from 2.10.36 -- and the rest of the firmware (bootloader, OS, drivers, boot scripts, etc) are all from whatever firmware is installed on the device. So it very possible for the 2.10.36 main application to work better in some firmware versions and worse in other versions. If you are offered the same update version (3.202.8), you have basically nothing to lose in taking the SD card out, booting up, performing the upgrade, inserting the SD card and rebooting.

**Comment by FlexxFR** [comment]
Ah, okay. Thanks for that explanation.

I did the upgrade, it's now running on 3.286.10, rebooting with SD card to enable RTSP again, re-enabled frigate and it appears to be better. At least it's running for a few hours straight enabled with frigate :) Let's see.

3.286.10 is the  only choice I have, but this is probably a different version for the rotating camera (or again a bit newer?)

**Comment by FlexxFR** [comment]
Just here to say that after the update the cam is still working fine :)
